services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
volumes:
 mongodb_data_container: